/**
 * JestInstrumentedRunner.ts — Jest implementation of IInstrumentedRunner.
 *
 * run() spawns Jest with the traceTransform injected for the target test file,
 * then parses the resulting JSONL trace file into a TimelineStore.
 *
 * parseEvents() reads a JSONL trace file produced by the instrumentation layer.
 */
import * as fs from 'fs';
import * as path from 'path';
import { Executor, BinaryResolver } from '@live-test-runner/runner';
import { IInstrumentedRunner } from './IInstrumentedRunner';
import {
  TimelineStore,
  Step,
  VariableSnapshot,
  LogEntry,
  ErrorEntry,
} from './TimelineStore';
import { TimelineEvent } from './TimelineEvent';
import { logger } from '../utils/logger';

const FILE = 'JestInstrumentedRunner.ts';

const TRACE_TRANSFORM_PATH = path.resolve(
  __dirname,
  'instrumentation',
  'traceTransform.js',
);

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export class JestInstrumentedRunner implements IInstrumentedRunner {
  private readonly executor = new Executor();
  private readonly binaryResolver = new BinaryResolver();

  constructor(private readonly _tmpDir: string) {}

  async run(options: {
    filePath: string;
    testFullName: string;
    projectRoot: string;
  }): Promise<TimelineStore> {
    const { filePath, testFullName, projectRoot } = options;
    logger.info(FILE, 'run', `Starting instrumented run — testFullName="${testFullName}" file="${filePath}"`);

    // 1. Temp file for JSONL trace output
    const traceFile = path.join(
      this._tmpDir,
      `ltr-trace-${Date.now()}-${Math.random().toString(36).slice(2)}.jsonl`,
    );

    // 2. Write a temporary Jest config that layers our transform on top of whatever
    //    the project already has. We use a CJS file so we can require() the existing
    //    config safely (most projects use CJS jest configs).
    const tempConfigPath = path.join(
      this._tmpDir,
      `ltr-jest-config-${Date.now()}.js`,
    );

    // Regex that matches any JS/TS source file under the project root (excluding
    // node_modules, which Jest already skips via transformIgnorePatterns).
    // This ensures imported source files (axiosConfig.js, incidentApi.js, etc.)
    // are also instrumented — not just the test file itself.
    // Normalize to forward slashes: jest normalises all file paths to forward
    // slashes before checking transform patterns.
    const escapedRoot = escapeRegex(projectRoot.replace(/\\/g, '/'));
    const srcTransformPattern = `^${escapedRoot}/(?!node_modules/).+\\.[jt]sx?$`;

    const configContent = `
'use strict';
// Temporary Jest config generated by Live Test Runner Timeline Debugger.
// Loads the project's existing config (if any) and overlays the trace transform.

let baseConfig = {};
try {
  const existing = require(${JSON.stringify(path.join(projectRoot, 'jest.config.js'))});
  baseConfig = (existing && existing.default) ? existing.default : existing;
} catch (_e1) {
  try {
    const existing = require(${JSON.stringify(path.join(projectRoot, 'jest.config.cjs'))});
    baseConfig = (existing && existing.default) ? existing.default : existing;
  } catch (_e2) {
    try {
      // Many projects put jest config inside package.json under a "jest" key
      const pkg = require(${JSON.stringify(path.join(projectRoot, 'package.json'))});
      if (pkg.jest) { baseConfig = pkg.jest; }
    } catch (_e3) {
      // No jest config found anywhere — start from empty base
    }
  }
}

// Normalise baseConfig.transform to a plain object so we stay compatible with
// all Jest versions (object format is the only format supported in Jest < 28).
// We build a NEW object with our specific-file entry first. JS objects preserve
// insertion order, so Jest's first-match will pick our entry before any catch-all
// (e.g. ^.+\\.[jt]sx?$) from the project config.
const baseTransformObj = Array.isArray(baseConfig.transform)
  ? Object.fromEntries(baseConfig.transform.map(([p, t, o]) => o ? [p, [t, o]] : [p, t]))
  : (baseConfig.transform || {});

// CRA and similar projects manage Jest config inside react-scripts and don't
// expose a transform in jest.config.js / package.json, so baseTransformObj ends
// up empty. When that happens, none of the source files imported by the test
// (axiosConfig.js, etc.) get transpiled — Jest loads them raw and hits their
// import/export statements. Add a catch-all babel-jest transform so every
// JS/TS file in the project gets compiled to CJS.
const hasGeneralJsTransform = Object.keys(baseTransformObj).some(pattern => {
  try { return new RegExp(pattern).test('src/foo.js'); } catch(_) { return false; }
});

let fallbackTransform = {};
if (!hasGeneralJsTransform) {
  const babelJestPath = require.resolve('babel-jest', { paths: [${JSON.stringify(projectRoot)}, __dirname] });
  // Prefer babel-preset-react-app (CRA) if present, otherwise @babel/preset-env
  let presets;
  try {
    const reactAppPreset = require.resolve('babel-preset-react-app', { paths: [${JSON.stringify(projectRoot)}] });
    presets = [[reactAppPreset, { runtime: 'automatic' }]];
  } catch(_) {
    try {
      const presetEnv = require.resolve('@babel/preset-env', { paths: [${JSON.stringify(projectRoot)}] });
      presets = [[presetEnv, { targets: { node: 'current' } }]];
    } catch(_) {
      presets = [];
    }
  }
  if (presets.length > 0) {
    fallbackTransform = {
      '^.+\\\\.[jt]sx?$': [babelJestPath, { configFile: false, presets }],
    };
  }
}

module.exports = {
  ...baseConfig,
  // rootDir must be the project root, not the /tmp/ directory where this config
  // file lives — otherwise Jest cannot find any test files.
  rootDir: ${JSON.stringify(projectRoot)},
  transform: {
    // Our entry first — matches only the exact file being debugged
    [${JSON.stringify(srcTransformPattern)}]: ${JSON.stringify(TRACE_TRANSFORM_PATH)},
    // Project's existing transforms (babel-jest, ts-jest, etc.)
    ...baseTransformObj,
    // Catch-all for CRA / projects where baseTransformObj is empty
    ...fallbackTransform,
  },
};
`;
    try {
      fs.writeFileSync(tempConfigPath, configContent, 'utf8');
    } catch (err) {
      logger.error(FILE, 'run', `Failed to write temp Jest config: ${tempConfigPath}`, err);
      throw err;
    }

    logger.debug(FILE, 'run', `Temp config written: ${tempConfigPath}`);
    logger.debug(FILE, 'run', `Trace output file: ${traceFile}`);
    logger.debug(FILE, 'run', `Transform path: ${TRACE_TRANSFORM_PATH} (exists=${fs.existsSync(TRACE_TRANSFORM_PATH)})`);

    // DEBUG — dump everything to a known file for easy inspection
    const debugLog =
      `traceFile: ${traceFile}\n` +
      `tempConfigPath: ${tempConfigPath}\n` +
      `TRACE_TRANSFORM_PATH: ${TRACE_TRANSFORM_PATH}\n` +
      `TRACE_TRANSFORM_PATH exists: ${fs.existsSync(TRACE_TRANSFORM_PATH)}\n` +
      `\n--- tempConfig ---\n${configContent}\n`;
    fs.writeFileSync(path.join(this._tmpDir, 'ltr-debug.log'), debugLog, 'utf8');

    // 3. Set the env var that traceRuntime.js reads to know where to write events
    process.env.TRACE_OUTPUT_FILE = traceFile;

    try {
      let binary: string;
      try {
        binary = this.binaryResolver.resolve(projectRoot);
        logger.debug(FILE, 'run', `Resolved Jest binary: ${binary}`);
      } catch (err) {
        logger.error(FILE, 'run', `Failed to resolve Jest binary for "${projectRoot}"`, err);
        throw err;
      }
      const escapedName = escapeRegex(testFullName);

      const result = await this.executor.run({
        binary,
        args: [
          '--watchAll=false',
          '--forceExit',
          '--no-bail',
          '--runTestsByPath',
          filePath,
          '--testNamePattern',
          `^${escapedName}$`,
          '--config',
          tempConfigPath,
        ],
        cwd: projectRoot,
      });

      logger.debug(FILE, 'run', `Jest instrumented run complete — passed=${result.passed}`);
      if (!result.passed) {
        logger.warn(FILE, 'run', `Jest exited with failure — stderr snippet: ${result.stderr.slice(0, 500)}`);
      }

      // DEBUG — append Jest output to the debug log
      fs.appendFileSync(
        path.join(this._tmpDir, 'ltr-debug.log'),
        `\n--- Jest stdout ---\n${result.stdout}\n--- Jest stderr ---\n${result.stderr}\n`,
      );
    } finally {
      // Clean up env var and temp config regardless of outcome
      delete process.env.TRACE_OUTPUT_FILE;
      try {
        fs.unlinkSync(tempConfigPath);
      } catch {
        /* ignore */
      }
    }

    // 4. Parse the trace file into a TimelineStore
    if (!fs.existsSync(traceFile)) {
      logger.error(FILE, 'run', `Trace file was not produced — no output to parse: ${traceFile}`);
    } else {
      const traceSize = fs.statSync(traceFile).size;
      logger.debug(FILE, 'run', `Trace file produced: ${traceFile} (${traceSize} bytes)`);
    }

    let store: TimelineStore;
    try {
      store = this.parseEvents(traceFile);
      logger.info(FILE, 'run', `Parsed trace — ${store.steps.length} steps, ${store.errors.length} errors`);
    } catch (err) {
      logger.error(FILE, 'run', `parseEvents threw for trace file: ${traceFile}`, err);
      throw err;
    } finally {
      try {
        fs.unlinkSync(traceFile);
      } catch {
        /* ignore */
      }
    }

    // Backfill metadata that parseEvents can't derive from events alone
    store.testFullName = testFullName;
    store.filePath = filePath;

    return store;
  }

  cancel(): void {
    this.executor.kill();
  }

  /**
   * Read a JSONL trace file produced by the instrumentation layer and assemble
   * a TimelineStore from it. Each line is a TimelineEvent JSON object.
   *
   * Only STEP/VAR/LOG/ERROR events whose functionName matches targetTestName are
   * kept — this filters out beforeEach, afterEach, and other tests in the file.
   *
   * Public so it can be exercised directly in tests / smoke checks.
   */
  parseEvents(filePath: string): TimelineStore {
    const store: TimelineStore = {
      testId: '',
      testFullName: '',
      filePath: '',
      steps: [],
      variables: new Map(),
      logs: new Map(),
      errors: [],
    };

    let raw: string;
    try {
      raw = fs.readFileSync(filePath, 'utf8');
    } catch (err) {
      logger.error(FILE, 'parseEvents', `Could not read trace file: "${filePath}"`, err);
      return store;
    }

    const lines = raw.split('\n').filter((l) => l.trim().length > 0);
    logger.debug(FILE, 'parseEvents', `Parsing ${lines.length} event lines from "${filePath}"`);

    let malformedCount = 0;
    for (const line of lines) {
      let event: TimelineEvent;
      try {
        event = JSON.parse(line) as TimelineEvent;
      } catch {
        malformedCount++;
        continue;
      }

      switch (event.type) {
        case 'STEP': {
          const step: Step = {
            stepId: event.stepId,
            line: event.line,
            file: event.file,
            functionName: event.functionName,
          };
          store.steps.push(step);
          // Seed the maps so consumers always get an array (never undefined)
          if (!store.variables.has(event.stepId)) {
            store.variables.set(event.stepId, []);
          }
          if (!store.logs.has(event.stepId)) {
            store.logs.set(event.stepId, []);
          }
          break;
        }

        case 'VAR': {
          const snapshot: VariableSnapshot = event.snapshot;
          const existing = store.variables.get(event.stepId) ?? [];
          existing.push(snapshot);
          store.variables.set(event.stepId, existing);
          break;
        }

        case 'LOG': {
          const entry: LogEntry = {
            text: event.args.join(' '),
            level: event.level as LogEntry['level'],
            timestamp: Date.now(),
          };
          const existing = store.logs.get(event.stepId) ?? [];
          existing.push(entry);
          store.logs.set(event.stepId, existing);
          break;
        }

        case 'ERROR': {
          const existing = store.errors.find((e) => e.stepId === event.stepId);
          if (existing) {
            existing.failureMessages.push(event.message);
          } else {
            const entry: ErrorEntry = {
              stepId: event.stepId,
              testName: store.testFullName,
              failureMessages: [event.message],
            };
            store.errors.push(entry);
          }
          break;
        }

        case 'ASSERT':
          // Assertions are not stored separately in TimelineStore for now —
          // failures are reported via ERROR events from the instrumentation layer.
          break;
      }
    }

    if (malformedCount > 0) {
      logger.warn(FILE, 'parseEvents', `Skipped ${malformedCount} malformed JSON lines in "${filePath}"`);
    }

    return store;
  }
}
