/**
 * JestInstrumentedRunner.ts — Jest implementation of IInstrumentedRunner.
 *
 * run() spawns Jest with the traceTransform injected for the target test file,
 * then parses the resulting JSONL trace file into a TimelineStore.
 *
 * parseEvents() reads a JSONL trace file produced by the instrumentation layer.
 */
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { Executor, BinaryResolver } from '@live-test-runner/runner';
import { IInstrumentedRunner } from './IInstrumentedRunner';
import { TimelineStore, Step, VariableSnapshot, LogEntry, ErrorEntry } from './TimelineStore';
import { TimelineEvent } from './TimelineEvent';

const TRACE_TRANSFORM_PATH = path.resolve(__dirname, 'instrumentation', 'traceTransform.js');

function escapeRegex(str: string): string {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

export class JestInstrumentedRunner implements IInstrumentedRunner {
  private readonly executor = new Executor();
  private readonly binaryResolver = new BinaryResolver();

  async run(options: {
    filePath: string;
    testFullName: string;
    projectRoot: string;
  }): Promise<TimelineStore> {
    const { filePath, testFullName, projectRoot } = options;

    // 1. Temp file for JSONL trace output
    const traceFile = path.join(
      os.tmpdir(),
      `ltr-trace-${Date.now()}-${Math.random().toString(36).slice(2)}.jsonl`,
    );

    // 2. Write a temporary Jest config that layers our transform on top of whatever
    //    the project already has. We use a CJS file so we can require() the existing
    //    config safely (most projects use CJS jest configs).
    const tempConfigPath = path.join(
      os.tmpdir(),
      `ltr-jest-config-${Date.now()}.js`,
    );

    // Escape filePath for use in the regex key of the transform map
    const escapedFileForRegex = escapeRegex(filePath).replace(/\//g, '\\/');

    const configContent = `
'use strict';
// Temporary Jest config generated by Live Test Runner Timeline Debugger.
// Loads the project's existing config (if any) and overlays the trace transform.

let baseConfig = {};
try {
  const existing = require(${JSON.stringify(path.join(projectRoot, 'jest.config.js'))});
  baseConfig = (existing && existing.default) ? existing.default : existing;
} catch (_e1) {
  try {
    const existing = require(${JSON.stringify(path.join(projectRoot, 'jest.config.cjs'))});
    baseConfig = (existing && existing.default) ? existing.default : existing;
  } catch (_e2) {
    // No CJS jest config — start from empty base
  }
}

// Normalise baseConfig.transform to array format so we can prepend our entry.
// Jest accepts both object { pattern: path } and array [[pattern, path]] forms.
const baseTransforms = Array.isArray(baseConfig.transform)
  ? baseConfig.transform
  : Object.entries(baseConfig.transform || {}).map(([p, v]) => Array.isArray(v) ? [p, ...v] : [p, v]);

module.exports = {
  ...baseConfig,
  // Our specific-file entry goes FIRST so Jest's first-match selects it before
  // the project's catch-all transformer (e.g. ^.+\\.[jt]sx?$).
  transform: [
    [${JSON.stringify('^' + escapedFileForRegex + '$')}, ${JSON.stringify(TRACE_TRANSFORM_PATH)}],
    ...baseTransforms,
  ],
};
`;
    fs.writeFileSync(tempConfigPath, configContent, 'utf8');

    // 3. Set the env var that traceRuntime.js reads to know where to write events
    process.env.TRACE_OUTPUT_FILE = traceFile;

    try {
      const binary = this.binaryResolver.resolve(projectRoot);
      const escapedName = escapeRegex(testFullName);

      await this.executor.run({
        binary,
        args: [
          '--watchAll=false',
          '--forceExit',
          '--no-bail',
          '--runTestsByPath',
          filePath,
          '--testNamePattern',
          `^${escapedName}$`,
          '--config',
          tempConfigPath,
        ],
        cwd: projectRoot,
      });
    } finally {
      // Clean up env var and temp config regardless of outcome
      delete process.env.TRACE_OUTPUT_FILE;
      try { fs.unlinkSync(tempConfigPath); } catch { /* ignore */ }
    }

    // 4. Parse the trace file into a TimelineStore
    let store: TimelineStore;
    try {
      store = this.parseEvents(traceFile);
    } finally {
      try { fs.unlinkSync(traceFile); } catch { /* ignore */ }
    }

    // Backfill metadata that parseEvents can't derive from events alone
    store.testFullName = testFullName;
    store.filePath = filePath;

    return store;
  }

  cancel(): void {
    this.executor.kill();
  }

  /**
   * Read a JSONL trace file produced by the instrumentation layer and assemble
   * a TimelineStore from it. Each line is a TimelineEvent JSON object.
   *
   * Public so it can be exercised directly in tests / smoke checks.
   */
  parseEvents(filePath: string): TimelineStore {
    const store: TimelineStore = {
      testId: '',
      testFullName: '',
      filePath: '',
      steps: [],
      variables: new Map(),
      logs: new Map(),
      errors: [],
    };

    const raw = fs.readFileSync(filePath, 'utf8');
    const lines = raw.split('\n').filter(l => l.trim().length > 0);

    for (const line of lines) {
      let event: TimelineEvent;
      try {
        event = JSON.parse(line) as TimelineEvent;
      } catch {
        // skip malformed lines
        continue;
      }

      switch (event.type) {
        case 'STEP': {
          const step: Step = {
            stepId:       event.stepId,
            line:         event.line,
            file:         event.file,
            functionName: event.functionName,
          };
          store.steps.push(step);
          // Seed the maps so consumers always get an array (never undefined)
          if (!store.variables.has(event.stepId)) { store.variables.set(event.stepId, []); }
          if (!store.logs.has(event.stepId))      { store.logs.set(event.stepId, []); }
          break;
        }

        case 'VAR': {
          const snapshot: VariableSnapshot = event.snapshot;
          const existing = store.variables.get(event.stepId) ?? [];
          existing.push(snapshot);
          store.variables.set(event.stepId, existing);
          break;
        }

        case 'LOG': {
          const entry: LogEntry = {
            text:      event.args.join(' '),
            level:     event.level as LogEntry['level'],
            timestamp: Date.now(),
          };
          const existing = store.logs.get(event.stepId) ?? [];
          existing.push(entry);
          store.logs.set(event.stepId, existing);
          break;
        }

        case 'ERROR': {
          const existing = store.errors.find(e => e.stepId === event.stepId);
          if (existing) {
            existing.failureMessages.push(event.message);
          } else {
            const entry: ErrorEntry = {
              stepId:          event.stepId,
              testName:        store.testFullName,
              failureMessages: [event.message],
            };
            store.errors.push(entry);
          }
          break;
        }

        case 'ASSERT':
          // Assertions are not stored separately in TimelineStore for now —
          // failures are reported via ERROR events from the instrumentation layer.
          break;
      }
    }

    return store;
  }
}
