name: Publish VSCode Extension

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      # 3️⃣ Install pnpm globally
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install deps
        run: pnpm install

      - name: Build
        run: pnpm run build
        # remove if you don’t have build step

      - name: Install vsce
        run: npm install -g vsce

      - name: Publish
        run: vsce publish -p $VSCE_PAT
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
